// ============ MOCK / DEMO DATA — V1 ============
// All case and publication data on this site is placeholder/demo content
// created to illustrate how IUPRN's database and reporting will function.
// No real investigations have been published yet.

const NAV_ITEMS = [
  { href: '#investigations', label: 'Investigations' },
  { href: '#database', label: 'Database' },
  { href: '#research', label: 'Research' },
  { href: '#methodology', label: 'Methodology' },
  { href: '#about', label: 'About' },
];

const STATUS_META = {
  'Investigating':        { badge: 'badge-investigating' },
  'Explained':            { badge: 'badge-explained' },
  'Probably Explained':   { badge: 'badge-probably' },
  'Inconclusive':         { badge: 'badge-inconclusive' },
  'Unresolved':           { badge: 'badge-unresolved' },
};

const RESEARCH_AREAS = [
  { key:'astronomy', name:'Astronomy', desc:'Unusual aerial and astronomical observations.' },
  { key:'physics', name:'Physics & Optics', desc:'Light, sound, motion and physical phenomena.' },
  { key:'psychology', name:'Psychology & Perception', desc:'Memory, perception, expectation and cognitive effects.' },
  { key:'earth', name:'Earth & Environment', desc:'Weather, atmospheric and environmental phenomena.' },
  { key:'technology', name:'Technology & Sensors', desc:'Measurement systems, cameras, audio and environmental sensors.' },
  { key:'data', name:'Data Science', desc:'Pattern detection, statistical analysis and evidence management.' },
];

const PROCESS_STEPS = [
  { n:'01', title:'Document', desc:'Record exactly what was observed, in the observer\u2019s own words, before any interpretation is added.' },
  { n:'02', title:'Preserve', desc:'Secure original photos, video, audio and their metadata so nothing is altered or lost.' },
  { n:'03', title:'Research', desc:'Examine environmental, astronomical, historical and human factors that could relate to the report.' },
  { n:'04', title:'Hypothesize', desc:'Develop multiple competing explanations, ordinary and extraordinary alike.' },
  { n:'05', title:'Test', desc:'Attempt to test or reproduce candidate explanations where it is safe and appropriate to do so.' },
  { n:'06', title:'Review', desc:'Submit findings to independent review and invite alternative interpretations.' },
  { n:'07', title:'Publish', desc:'Report the conclusion the evidence supports \u2014 including how much remains uncertain.' },
];

const VALUES = [
  { name:'Curiosity', desc:'We take unusual reports seriously enough to look closely at them.' },
  { name:'Scientific skepticism', desc:'We hold explanations \u2014 ordinary and extraordinary \u2014 to the same standard of evidence.' },
  { name:'Intellectual honesty', desc:'We report what the evidence shows, not what would make a better story.' },
  { name:'Respect for witnesses', desc:'People who report something they cannot explain deserve to be heard without ridicule.' },
  { name:'Evidence preservation', desc:'Original material and metadata are protected from the moment a case is opened.' },
  { name:'Open inquiry', desc:'Findings are published for scrutiny, including cases where we could be wrong.' },
];

const ROLES = [
  { title:'Student Researcher', desc:'Learn IUPRN\u2019s methodology and assist active investigations under supervision.', tags:['Beginner friendly','Training provided'] },
  { title:'Field Investigator', desc:'Document observations on location using IUPRN\u2019s evidence-collection protocols.', tags:['Travel may be required','Protocol training'] },
  { title:'Data Researcher', desc:'Analyse case data, look for patterns across reports, and maintain the case database.', tags:['Remote friendly','Statistics helpful'] },
  { title:'Astronomy Researcher', desc:'Assess astronomical explanations \u2014 satellites, planets, meteors, conjunctions \u2014 for aerial reports.', tags:['Remote friendly'] },
  { title:'Psychology Researcher', desc:'Study perception, memory and expectation effects in witness accounts.', tags:['Remote friendly'] },
  { title:'Technology Team', desc:'Build and maintain sensors, cameras and measurement tools used in field investigations.', tags:['Hardware/software'] },
  { title:'Scientific Advisor', desc:'Provide expert guidance and methodological review across research areas.', tags:['Credentialed experts'] },
];

// ---------------- CASES ----------------
const CASES = [
  {
    id:'IUPRN-2026-001',
    demo:true,
    title:'Unusual Aerial Light Observation',
    date:'2026-01-14',
    year:2026,
    region:'Western India',
    phenomenon:'Aerial light',
    area:'astronomy',
    status:'Probably Explained',
    evidence:['Photograph','Witness Report','Environmental Data'],
    claim:'A resident reported a bright, slow-moving light that appeared to hover and change colour over a rural horizon for roughly six minutes before fading from view.',
    environment:'Clear night sky, low humidity, light westerly wind. No cloud cover reported. Observation made shortly after local sunset during nautical twilight.',
    hypotheses:[
      { id:'H1', name:'Aircraft', outcome:'weakened', note:'No matching flight-tracking data for the time and bearing reported.' },
      { id:'H2', name:'Satellite', outcome:'weakened', note:'Motion described was inconsistent with typical satellite pass speed.' },
      { id:'H3', name:'Astronomical object', outcome:'supported', note:'Venus was near the reported bearing and altitude at the time of observation.' },
      { id:'H4', name:'Atmospheric phenomenon', outcome:'inconclusive', note:'Atmospheric scintillation could plausibly account for the colour changes described.' },
      { id:'H5', name:'Optical/camera artifact', outcome:'inconclusive', note:'Submitted photograph shows lens flare consistent with a bright point source.' },
      { id:'H6', name:'Other', outcome:'weakened', note:'No other candidate explanation was identified.' },
    ],
    investigation:'The reported bearing, elevation and time were cross-checked against planetarium software and public flight-tracking archives. The submitted photograph was examined for metadata and optical artifacts.',
    findings:'The reported position and apparent brightness closely matched Venus\u2019s position that evening. Low-altitude atmospheric scintillation is a known cause of the twinkling and colour-shifting described near the horizon.',
    conclusion:'Available evidence currently favors an ordinary explanation \u2014 Venus, viewed low on the horizon under atmospheric conditions that can exaggerate twinkling and colour. Further evidence may change this assessment.',
    confidence:'Moderate-to-high confidence in the astronomical explanation; case kept open for supplementary witness data.',
    notes:'Witness was cooperative and provided a clear bearing estimate using a compass app, which aided reconstruction significantly.',
    related:['Astronomy','Physics & Optics'],
    timeline:[
      { date:'2026-01-14', label:'Report received' },
      { date:'2026-01-15', label:'Evidence preserved & catalogued' },
      { date:'2026-01-18', label:'Astronomical cross-check completed' },
      { date:'2026-01-24', label:'Flight-tracking archives reviewed' },
      { date:'2026-02-02', label:'Preliminary hypothesis review' },
      { date:'2026-02-20', label:'Assessment published: Probably Explained' },
    ],
  },
  {
    id:'IUPRN-2026-002',
    demo:true,
    title:'Recurring Nocturnal Humming Sound',
    date:'2026-02-03',
    year:2026,
    region:'Northern India',
    phenomenon:'Unexplained sound',
    area:'physics',
    status:'Investigating',
    evidence:['Audio Recording','Witness Report'],
    claim:'Several residents of the same neighbourhood independently reported a low, continuous humming sound audible mainly at night, with no identifiable source.',
    environment:'Reports cluster in a residential area near industrial infrastructure. No unusual weather noted.',
    hypotheses:[
      { id:'H1', name:'Industrial equipment', outcome:'pending', note:'Nearby facilities have not yet been surveyed for matching frequency signatures.' },
      { id:'H2', name:'Infrasound / wind interaction', outcome:'pending', note:'Terrain and structure geometry have not yet been assessed.' },
      { id:'H3', name:'Auditory phenomenon (perception)', outcome:'pending', note:'A subset of "hums" reported worldwide are linked to individual auditory perception rather than an external sound source.' },
      { id:'H4', name:'Other', outcome:'pending', note:'Not yet assessed.' },
    ],
    investigation:'Audio recordings are being spectrally analysed. A field visit with calibrated sound-level and frequency-analysis equipment is being scheduled.',
    findings:'Preliminary spectral analysis shows a persistent low-frequency component; source not yet isolated.',
    conclusion:'Investigation ongoing. No conclusion has been reached.',
    confidence:'Not yet applicable \u2014 case is in the evidence-gathering stage.',
    notes:'Multiple independent witnesses strengthen the case for a real external sound source, but do not by themselves indicate its cause.',
    related:['Physics & Optics','Technology & Sensors'],
    timeline:[
      { date:'2026-02-03', label:'Report received' },
      { date:'2026-02-05', label:'Audio evidence preserved' },
      { date:'2026-02-14', label:'Spectral analysis started' },
      { date:'2026-03-01', label:'Field visit scheduled' },
    ],
  },
  {
    id:'IUPRN-2025-014',
    demo:true,
    title:'Photographed Anomaly Near Temple Grounds',
    date:'2025-11-09',
    year:2025,
    region:'Southern India',
    phenomenon:'Photographic anomaly',
    area:'physics',
    status:'Explained',
    evidence:['Photograph'],
    claim:'A visitor submitted a photograph showing an unexplained streak of light near temple grounds at dusk, believed by the submitter to be unusual.',
    environment:'Low-light conditions, handheld smartphone photograph, long shutter exposure.',
    hypotheses:[
      { id:'H1', name:'Insect near lens', outcome:'supported', note:'Streak geometry and blur pattern are consistent with an insect illuminated by flash at close range.' },
      { id:'H2', name:'Sensor artifact', outcome:'weakened', note:'Ruled out after examining unedited image metadata.' },
      { id:'H3', name:'Other', outcome:'weakened', note:'No other explanation was required once H1 was tested.' },
    ],
    investigation:'A controlled re-creation was attempted using the same phone model, flash setting and a moving insect at a similar distance.',
    findings:'The re-created photograph produced a near-identical streak pattern.',
    conclusion:'Explained. The anomaly is consistent with an insect passing close to the camera lens during a flash exposure.',
    confidence:'High confidence.',
    notes:'A good example of why reproduction attempts matter before any unusual conclusion is drawn.',
    related:['Physics & Optics','Technology & Sensors'],
    timeline:[
      { date:'2025-11-09', label:'Report received' },
      { date:'2025-11-11', label:'Image metadata reviewed' },
      { date:'2025-11-20', label:'Reproduction test conducted' },
      { date:'2025-11-28', label:'Assessment published: Explained' },
    ],
  },
  {
    id:'IUPRN-2025-011',
    demo:true,
    title:'Unidentified Object on Coastal Radar-Adjacent Report',
    date:'2025-09-22',
    year:2025,
    region:'Western Coast',
    phenomenon:'Aerial object',
    area:'astronomy',
    status:'Inconclusive',
    evidence:['Witness Report','Environmental Data'],
    claim:'Fishermen reported an unusual fast-moving object over open water at dawn, visible for under ten seconds.',
    environment:'Overcast, low visibility, brief sighting window.',
    hypotheses:[
      { id:'H1', name:'Aircraft', outcome:'inconclusive', note:'No corroborating flight data available for the exact time and location.' },
      { id:'H2', name:'Weather balloon / debris', outcome:'inconclusive', note:'Plausible but unverifiable without physical recovery.' },
      { id:'H3', name:'Bird flock at distance', outcome:'inconclusive', note:'Cannot be ruled out given the short viewing window.' },
    ],
    investigation:'Witnesses were interviewed separately. No photographic or video evidence was available, and no physical trace was recovered.',
    findings:'Evidence is limited to verbal testimony from two witnesses whose accounts partially agree.',
    conclusion:'Inconclusive. Available evidence is insufficient to favour any hypothesis over the others.',
    confidence:'Low confidence in any single explanation; this reflects the evidence available, not a paranormal finding.',
    notes:'Case remains open for further evidence; short sighting windows are a common limiting factor.',
    related:['Astronomy'],
    timeline:[
      { date:'2025-09-22', label:'Report received' },
      { date:'2025-09-25', label:'Witness interviews conducted' },
      { date:'2025-10-06', label:'Assessment published: Inconclusive' },
    ],
  },
  {
    id:'IUPRN-2025-006',
    demo:true,
    title:'Reported Cold Spot in a Historic Building',
    date:'2025-06-02',
    year:2025,
    region:'North India',
    phenomenon:'Environmental anomaly',
    area:'earth',
    status:'Explained',
    evidence:['Environmental Data','Witness Report'],
    claim:'Visitors to a historic building reported a distinct, localised cold sensation in one corridor, which some interpreted as unusual.',
    environment:'Old masonry construction, uneven ventilation, adjacent to a below-grade water channel.',
    hypotheses:[
      { id:'H1', name:'Airflow / draught', outcome:'supported', note:'Thermal imaging identified a consistent draught from a gap connected to a below-grade channel.' },
      { id:'H2', name:'Thermal mass of old masonry', outcome:'supported', note:'Thick stone walls retain cold and release it slowly, exaggerating the temperature difference.' },
      { id:'H3', name:'Other', outcome:'weakened', note:'Not required once environmental causes were confirmed.' },
    ],
    investigation:'A thermal camera and calibrated thermometers were used to map temperature across the corridor over several hours.',
    findings:'A measurable, explainable temperature gradient was confirmed and traced to airflow and building materials.',
    conclusion:'Explained. The cold spot is consistent with draught and thermal mass effects common in old masonry buildings.',
    confidence:'High confidence.',
    notes:'A recurring theme: many "cold spot" reports have straightforward architectural explanations once measured.',
    related:['Earth & Environment','Technology & Sensors'],
    timeline:[
      { date:'2025-06-02', label:'Report received' },
      { date:'2025-06-10', label:'Thermal survey conducted' },
      { date:'2025-06-19', label:'Assessment published: Explained' },
    ],
  },
  {
    id:'IUPRN-2025-002',
    demo:true,
    title:'Recurring Sense of Presence Reported by Multiple Occupants',
    date:'2025-02-11',
    year:2025,
    region:'Eastern India',
    phenomenon:'Perceptual experience',
    area:'psychology',
    status:'Unresolved',
    evidence:['Witness Report'],
    claim:'Multiple occupants of a residence independently described a recurring sense of "being watched" in one room, without any accompanying sensory evidence.',
    environment:'Older residential structure; no unusual environmental readings recorded during a brief visit.',
    hypotheses:[
      { id:'H1', name:'Infrasound below hearing threshold', outcome:'inconclusive', note:'A brief measurement pass detected no significant infrasound, but monitoring duration was limited.' },
      { id:'H2', name:'Expectation / shared suggestion effect', outcome:'inconclusive', note:'Occupants had discussed the sensation with each other before IUPRN was contacted, which cannot be ruled out as a contributing factor.' },
      { id:'H3', name:'Carbon monoxide or air-quality factors', outcome:'weakened', note:'Air quality readings taken during the visit were within normal ranges.' },
      { id:'H4', name:'Other / not yet identified', outcome:'pending', note:'No further physical cause has been identified with current evidence.' },
    ],
    investigation:'A single field visit was conducted with basic environmental sensors. Extended monitoring has not yet been arranged.',
    findings:'No physical anomaly was detected during the visit; the reported experience itself was not observed by investigators.',
    conclusion:'Unresolved. Current evidence is insufficient to identify a cause. This does not indicate a paranormal explanation \u2014 it reflects the limits of what has been measured so far.',
    confidence:'Low confidence in any hypothesis; case remains open pending extended monitoring.',
    notes:'A candidate case for a longer-duration sensor deployment.',
    related:['Psychology & Perception','Earth & Environment'],
    timeline:[
      { date:'2025-02-11', label:'Report received' },
      { date:'2025-02-19', label:'Field visit conducted' },
      { date:'2025-03-05', label:'Assessment published: Unresolved' },
    ],
  },
];

// ---------------- PUBLICATIONS ----------------
const PUBLICATIONS = [
  {
    title:'A Standardized Framework for Investigating Unexplained Aerial Observations in Indian Airspace',
    authors:'IUPRN Astronomy & Data Working Group',
    date:'2026-01',
    category:'Methodology',
    peerReviewed:false,
    status:'IUPRN preliminary report',
    abstract:'We propose a repeatable protocol for triaging aerial-observation reports using astronomical, meteorological and flight-traffic cross-referencing prior to deeper field investigation.',
  },
  {
    title:'Case Report: Assessment of a Recurring Nocturnal Sound in a Northern Indian Residential Area',
    authors:'IUPRN Physics & Sensors Team',
    date:'2026-02',
    category:'Case Reports',
    peerReviewed:false,
    status:'IUPRN preliminary report',
    abstract:'A working case report documenting the evidence-gathering phase for IUPRN-2026-002, including preliminary spectral analysis of submitted audio.',
  },
  {
    title:'Suggestion, Expectation and the "Sense of Presence": A Literature Review',
    authors:'IUPRN Psychology Research Group',
    date:'2025-12',
    category:'Literature Reviews',
    peerReviewed:false,
    status:'IUPRN preliminary report',
    abstract:'A review of existing published research on infrasound, suggestion effects and environmental factors associated with reported "sense of presence" experiences, and its relevance to IUPRN case triage.',
  },
  {
    title:'Five-Year Pattern Analysis of Publicly Reported Aerial Phenomena (External Dataset)',
    authors:'External collaborators, in review',
    date:'2025-10',
    category:'Data Analysis',
    peerReviewed:true,
    status:'Peer-reviewed (external journal, in review)',
    abstract:'A statistical analysis of a publicly available aerial-phenomena reporting dataset, examining seasonal, geographic and time-of-day patterns as a reference point for IUPRN\u2019s own case intake.',
  },
  {
    title:'Explaining the Unexplained: A Public Guide to How Investigation Works',
    authors:'IUPRN Education Team',
    date:'2025-09',
    category:'Educational Resources',
    peerReviewed:false,
    status:'IUPRN educational resource',
    abstract:'A plain-language explainer for the public on the difference between an observation, a hypothesis, evidence, an explanation, and an unresolved case.',
  },
  {
    title:'Reproducing a Reported Photographic Anomaly: Insect-Near-Lens Flash Artifacts',
    authors:'IUPRN Physics & Sensors Team',
    date:'2025-11',
    category:'Experimental Studies',
    peerReviewed:false,
    status:'IUPRN preliminary report',
    abstract:'An experimental reproduction of a photographic anomaly reported near temple grounds, testing the insect-near-lens hypothesis under controlled conditions.',
  },
];

// ---------------- EXPLAINED ARCHIVE (subset, for homepage feature) ----------------
const EXPLAINED_HIGHLIGHTS = CASES.filter(c => c.status === 'Explained');
